export const MOVIE_DATA = [
  {
    _id: "65de07699c0ae21b6a73836a",
    userId: "65d64c48597f755f25d8b49a",
    authorizedUsers: ["65d64c48597f755f25d8b49a"],
    cast: [
      {
        groupTitle: "Starring",
        members: [
          { name: "Albert Will", title: "Max Cliber" },
          { name: "Sam Exler", title: "Roham" },
        ],
      },
      {
        groupTitle: "Camera/Grip",
        members: [
          { name: "John Doe", role: "Director of Photography" },
          { name: "Jane Smith", role: "Key Grip" },
        ],
      },
    ],
    writers: ["Smith Will", "James Seen"],
    movieTitle: "Blade Runner 2049",
    movieUrl: "/assets/movie.mp4",
    movieTrailerUrl: "/assets/trailer.mp4",
    movieDescription:
      "The film is set in a dystopian future Los Angeles of 2019, in which synthetic humans known as replicants are bio-engineered.",
    thumbnailUrl: "/assets/thumbnail.png",
    yearMade: "2017",
    likes: 95,
    dateUploaded: "02/27/2024",
    shortFilm: false,
    genre: "Sci Fi",
    tags: [],
    isActive: false,
    runTime: "165 m",
    contentStatus: "pending",
    contentType: "Movie",
    maturityRating: "Rated R",
    createdAt: "2024-02-27T16:01:45.630+00:00",
    updatedAt: { $date: { $numberLong: "1709049705630" } },
    __v: 0,
  },
  {
    _id: "65de07699c0ae21b6a738344a",
    userId: "65d64c48597f755f25d8b49a",
    authorizedUsers: ["65d64c48597f755f25d8b49a"],
    cast: [
      {
        groupTitle: "Starring",
        members: [
          { name: "Albert Will", title: "Max Cliber" },
          { name: "Sam Exler", title: "Roham" },
        ],
      },
      {
        groupTitle: "Camera/Grip",
        members: [
          { name: "John Doe", role: "Director of Photography" },
          { name: "Jane Smith", role: "Key Grip" },
        ],
      },
    ],
    writers: ["Smith Will", "James Seen"],
    movieTitle: "Dune: Part Two",
    movieUrl: "/assets/movie.mp4",
    movieTrailerUrl: "/assets/trailer.mp4",
    movieDescription:
      "The film is set in a dystopian future Los Angeles of 2019, in which synthetic humans known as replicants are bio-engineered.",
    thumbnailUrl: "/assets/thumbnail.png",
    yearMade: "2017",
    likes: 95,
    dateUploaded: "02/27/2024",
    shortFilm: false,
    genre: "Sci Fi",
    tags: [],
    isActive: false,
    runTime: "165 m",
    contentStatus: "pending",
    contentType: "Movie",
    maturityRating: "Rated R",
    createdAt: "2024-02-27T16:01:45.630+00:00",
    updatedAt: { $date: { $numberLong: "1709049705630" } },
    __v: 0,
  },
];
